### ISSUE TITLE
Matching Bug With Subcommand

### ISSUE THREAD

**Issue by ClementMastin** [cdlm/clap-st#13]
When I have that:

```smalltalk
sub := (ClapCommand withName: 'this') addFlag: (ClapFlag withName: 'force').
pos := ClapPositional withName: 'class'.
command := (ClapCommand withName: 'foo') addPositional: pos;addSubcommand: sub.
context := ClapContext on: #('foo' 'this' 'Object').
command matchOn: context
```
It returns a ClapCommandMatch with a ClapPositionalMatch

**Comment by cdlm** [comment]
I believe that's not the case anymore. Now the subcommands are responsible for consuming to the end of the stream, and what remains is considered as leftover.
