### ISSUE TITLE
Mocketry Install

### ISSUE THREAD

**Issue by ClementMastin** [cdlm/clap-st#5]
It could be good if when you load Clap, it also load Mocketry because of the tests

**Comment by cdlm** [comment]
Doesn't the baseline already do it ?

**Comment by ClementMastin** [comment]
I tested it now and it doesn't install

**Comment by cdlm** [comment]
Ok… if you can make it load both packages by default, it would be good. However I think it should be possible to load `Clap-Core` alone (e.g. in a deployment scenario).

**Comment by cdlm** [comment]
Works for me…

**Comment by ClementMastin** [comment]
I didn't load Clap with what the Readme indicates.I load it with Iceberg so it's maybe a problem coming from Iceberg.

**Comment by cdlm** [comment]
Ah then it's a case of [PEBCAK](https://en.wikipedia.org/wiki/User_error) :p

Iceberg has no notion of dependency so if you asked it to load Clap-Core it loaded only that. That's what's the baseline is for: it specifies what groups of packages are interesting and in which order to load them.
